### ISSUE TITLE
Why Bert-VITS2 use  AudoModelForMaskedLM instead of default BertModel?

### ISSUE THREAD

**Issue by JohnHerry** [foocker/Bert-VITS2-Faster#1]
as  title

**Comment by foocker** [comment]
> as title

maybe you can reference 'chinese-roberta-wwm-ext-large'

**Comment by JohnHerry** [comment]
I did 

> > as title
> 
> maybe you can reference 'chinese-roberta-wwm-ext-large'

I did not find the answer, can you please give a direct resp? thank you.

**Comment by foocker** [comment]
> I did
> 
> > > as title
> > 
> > 
> > maybe you can reference 'chinese-roberta-wwm-ext-large'
> 
> I did not find the answer, can you please give a direct resp? thank you.

i am not a nlp engineer, so as you know. you can issue in Bert-VITS2.
