### ISSUE TITLE
About Bert-VITS2 stochastic duration predictor training problem.

### ISSUE THREAD

**Issue by 0913ktg** [foocker/Bert-VITS2-Faster#2]
Hello fooker,

I am a speech synthesis model developer from South Korea.

Recently, I have started training a Korean version of fishaudio's Bert-VITS2. During the training, I encountered some issues with the stochastic duration predictor's adversarial training.

I suspect this might be a problem unique to the Korean language. While reviewing the issue, I came across your Bert-VITS2-Faster, which I believe to be a promising piece of work, though I haven't tested it yet.

My goal is to implement a multilingual Bert-VITS2 that supports Chinese, English, Japanese, and Korean. I am looking forward to communicating and collaborating with you in this endeavor.

I would like to inquire if you have ever faced any issues with the duration predictor training while training Bert-VITS2 in other languages. If you have encountered and resolved similar challenges, I would be immensely grateful if you could share your solutions.

Thank you once again for sharing your excellent code. Have a great day.

Best regards,
0913ktg.

**Comment by foocker** [comment]
> Hello fooker,
> 
> I am a speech synthesis model developer from South Korea.
> 
> Recently, I have started training a Korean version of fishaudio's Bert-VITS2. During the training, I encountered some issues with the stochastic duration predictor's adversarial training.
> 
> I suspect this might be a problem unique to the Korean language. While reviewing the issue, I came across your Bert-VITS2-Faster, which I believe to be a promising piece of work, though I haven't tested it yet.
> 
> My goal is to implement a multilingual Bert-VITS2 that supports Chinese, English, Japanese, and Korean. I am looking forward to communicating and collaborating with you in this endeavor.
> 
> I would like to inquire if you have ever faced any issues with the duration predictor training while training Bert-VITS2 in other languages. If you have encountered and resolved similar challenges, I would be immensely grateful if you could share your solutions.
> 
> Thank you once again for sharing your excellent code. Have a great day.
> 
> Best regards, 0913ktg.

Thanks for the recognition, but the main purpose of my repo is inference (pt->onnx->trt), not training, and I have never trained a speech model, so I'm sorry, I can't help you with your question. You can raise an official issue regarding this issue.
