### ISSUE TITLE
有考虑支持Bert-VITS2的2.3版本吗？

### ISSUE THREAD

**Issue by DoiiarX** [foocker/Bert-VITS2-Faster#3]
有考虑支持Bert-VITS2的2.3版本吗？

**Comment by foocker** [comment]
> 有考虑支持Bert-VITS2的2.3版本吗？

没有了，以前零时做的。

**Comment by DoiiarX** [comment]
> > 有考虑支持Bert-VITS2的2.3版本吗？
> 
> 没有了，以前临时做的。

作者有空加个联系方式吗？我打算在2.3版本自己做一个。
