### ISSUE TITLE
大佬。这个仓库在被提交之前有检查吗?

### ISSUE THREAD

**Issue by DoiiarX** [foocker/Bert-VITS2-Faster#5]
这个仓库在被提交之前有检查吗?我已经发现三处前向神经网络forward函数的错误了。太难受了。

**Comment by foocker** [comment]
> 这个仓库在被提交之前有检查吗?我已经发现三处前向神经网络forward函数的错误了。太难受了。

啥错误？

**Comment by DoiiarX** [comment]
> > 这个仓库在被提交之前有检查吗?我已经发现三处前向神经网络forward函数的错误了。太难受了。
> 
> 啥错误？提交前跑测没啥问题。

之前训练时会显示同一个变量被赋值两次，我检查后发现是变量参数不够，所以报错。
当时我提交了pr，我以为bug就这个。
![image](https://github.com/foocker/Bert-VITS2-Faster/assets/25550075/6446cba8-466a-4847-8d33-3921f83fc78e)


但是这类bug出现了两三次。

之后bug在于reverse的问题，需要添加不同的reverse的处理方案。

类似于这样。

![image](https://github.com/foocker/Bert-VITS2-Faster/assets/25550075/7e43ab2a-a85e-4d8c-99b9-10d98ce34890)

最后改动了两个文件，非常多的代码才可以开始训练。
![image](https://github.com/foocker/Bert-VITS2-Faster/assets/25550075/158929d2-06c7-4b81-9a87-80ff3d7d2187)

但是训练完成之后，导出onnx成功，却没法转trt，显示“无法识别的网络结构”

**Comment by DoiiarX** [comment]
> > 这个仓库在被提交之前有检查吗?我已经发现三处前向神经网络forward函数的错误了。太难受了。
> 
> 啥错误？提交前跑测没啥问题。

还有就是，想请教一下，是有意这样子删除reverse的吗？

![image](https://github.com/foocker/Bert-VITS2-Faster/assets/25550075/d3d7f034-7af5-4856-8c88-79b811f92f6a)

**Comment by foocker** [comment]
> > > 这个仓库在被提交之前有检查吗?我已经发现三处前向神经网络forward函数的错误了。太难受了。
> > 
> > 
> > 啥错误？提交前跑测没啥问题。
> 
> 还有就是，想请教一下，是有意这样子删除reverse的吗？
> 
> ![image](https://private-user-images.githubusercontent.com/25550075/326224378-d3d7f034-7af5-4856-8c88-79b811f92f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTk4MzMsIm5iZiI6MTcxNDM1OTUzMywicGF0aCI6Ii8yNTU1MDA3NS8zMjYyMjQzNzgtZDNkN2YwMzQtN2FmNS00ODU2LThjODgtNzliODExZjkyZjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAyNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MDNmZDRjMDkzMDZiOWFmYjVhMmEyOWRiMGQ0OGMwMzhjYzRjOGNiZjM1ZmRiNWMxZGY2OTEzNjk2NTRiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.52oqyyzuJlIWtWNqPlbO5Njlwzw412omoq5c5nkn2rk)

哦哦，是这样的。我这个只是部署的，不涉及到训练，原始的代码，需要做这些修改，才能转trt。 所以，你如果要同时保持训练和部署的功能，就像我这样，把原始的训练代码改了。确实有很多小地方需要修改。

**Comment by DoiiarX** [comment]
> > > > 这个仓库在被提交之前有检查吗？我已经发现三处前向神经网络转发函数的错误了。太难受了。
> > > 
> > > 
> > > 啥错误？提交前跑测没啥问题。
> > 
> > 
> > 还有就是，想请教一下，是有意这样子删除reverse的吗？
> > ![image](https://private-user-images.githubusercontent.com/25550075/326224378-d3d7f034-7af5-4856-8c88-79b811f92f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTk4MzMsIm5iZiI6MTcxNDM1OTUzMywicGF0aCI6Ii8yNTU1MDA3NS8zMjYyMjQzNzgtZDNkN2YwMzQtN2FmNS00ODU2LThjODgtNzliODExZjkyZjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAyNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MDNmZDRjMDkzMDZiOWFmYjVhMmEyOWRiMGQ0OGMwMzhjYzRjOGNiZjM1ZmRiNWMxZGY2OTEzNjk2NTRiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.52oqyyzuJlIWtWNqPlbO5Njlwzw412omoq5c5nkn2rk)
> 
> 哦哦，是这样的。我这个只是部署的，不涉及到训练，原始的代码，需要做这些修改，才能转trt。所以，你如果要同时保持训练和部署的功能，就像我这样，把原始的训练代码改了。确实有很多小地方需要修改。还有一些注意事项，转trt后，有部分字，效果会比较差，所以，我这里有onnx+trt的组合，如果要完全的trt且保效，就又产生了另外的工作了。模型的优化，在训练端，需要实验来改模块，同时保证其转trt不过分失效。
> 
> 还有一种简单的方式，原始训练模型的代码保持不变，只需要把模型文件替换，用我提供的代码做模型转化和推理就行。但是这种方式的弊端在于，模型的版本不同，你就得改模型转化的代码。如果，两者齐头并进，则像我第一段说的那样做。
> 
> 总的来说，产生这个原因的问题在于：这个只是部署测试的例子， 原始模型在我选的这个版本中，并没有达到私有部署的效果。如果他现在的版本，或者我选的这个版本的算法效果符合你的需求，或者你坚信后期版本会达到你的效果，那么，两者都做吧。

由于出现过版本重大修复，我使用2.0.2.1的版本做模型转化， 会显示”**无法识别的网络结构**“。作者是用2.0.2版本做的吗？是否是我使用方法问题，还是说因为版本不兼容？

如果是版本不兼容，我想要希望您可以给我2.0.2的训练代码。感激不尽。

**Comment by DoiiarX** [comment]
> > > > 这个仓库在被提交之前有检查吗？我已经发现三处前向神经网络转发函数的错误了。太难受了。
> > > 
> > > 
> > > 啥错误？提交前跑测没啥问题。
> > 
> > 
> > 还有就是，想请教一下，是有意这样子删除reverse的吗？
> > ![image](https://private-user-images.githubusercontent.com/25550075/326224378-d3d7f034-7af5-4856-8c88-79b811f92f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTk4MzMsIm5iZiI6MTcxNDM1OTUzMywicGF0aCI6Ii8yNTU1MDA3NS8zMjYyMjQzNzgtZDNkN2YwMzQtN2FmNS00ODU2LThjODgtNzliODExZjkyZjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAyNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MDNmZDRjMDkzMDZiOWFmYjVhMmEyOWRiMGQ0OGMwMzhjYzRjOGNiZjM1ZmRiNWMxZGY2OTEzNjk2NTRiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.52oqyyzuJlIWtWNqPlbO5Njlwzw412omoq5c5nkn2rk)
> 
> 哦哦，是这样的。我这个只是部署的，不涉及到训练，原始的代码，需要做这些修改，才能转trt。所以，你如果要同时保持训练和部署的功能，就像我这样，把原始的训练代码改了。确实有很多小地方需要修改。还有一些注意事项，转trt后，有部分字，效果会比较差，所以，我这里有onnx+trt的组合，如果要完全的trt且保效，就又产生了另外的工作了。模型的优化，在训练端，需要实验来改模块，同时保证其转trt不过分失效。
> 
> 还有一种简单的方式，原始训练模型的代码保持不变，只需要把模型文件替换，用我提供的代码做模型转化和推理就行。但是这种方式的弊端在于，模型的版本不同，你就得改模型转化的代码。如果，两者齐头并进，则像我第一段说的那样做。
> 
> 总的来说，产生这个原因的问题在于：这个只是部署测试的例子， 原始模型在我选的这个版本中，并没有达到私有部署的效果。如果他现在的版本，或者我选的这个版本的算法效果符合你的需求，或者你坚信后期版本会达到你的效果，那么，两者都做吧。

我理解的思路是，用某个版本的代码训练，则在该版本模型代码全部去除正向传播。用作者你的代码进行onnx和trt模型的导出，然后再推理。请问是否正确。

**Comment by foocker** [comment]
> > > > > 这个仓库在被提交之前有检查吗？我已经发现三处前向神经网络转发函数的错误了。太难受了。
> > > > 
> > > > 
> > > > 啥错误？提交前跑测没啥问题。
> > > 
> > > 
> > > 还有就是，想请教一下，是有意这样子删除reverse的吗？
> > > ![image](https://private-user-images.githubusercontent.com/25550075/326224378-d3d7f034-7af5-4856-8c88-79b811f92f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTk4MzMsIm5iZiI6MTcxNDM1OTUzMywicGF0aCI6Ii8yNTU1MDA3NS8zMjYyMjQzNzgtZDNkN2YwMzQtN2FmNS00ODU2LThjODgtNzliODExZjkyZjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAyNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MDNmZDRjMDkzMDZiOWFmYjVhMmEyOWRiMGQ0OGMwMzhjYzRjOGNiZjM1ZmRiNWMxZGY2OTEzNjk2NTRiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.52oqyyzuJlIWtWNqPlbO5Njlwzw412omoq5c5nkn2rk)
> > 
> > 
> > 哦哦，是这样的。我这个只是部署的，不涉及到训练，原始的代码，需要做这些修改，才能转trt。所以，你如果要同时保持训练和部署的功能，就像我这样，把原始的训练代码改了。确实有很多小地方需要修改。还有一些注意事项，转trt后，有部分字，效果会比较差，所以，我这里有onnx+trt的组合，如果要完全的trt且保效，就又产生了另外的工作了。模型的优化，在训练端，需要实验来改模块，同时保证其转trt不过分失效。
> > 还有一种简单的方式，原始训练模型的代码保持不变，只需要把模型文件替换，用我提供的代码做模型转化和推理就行。但是这种方式的弊端在于，模型的版本不同，你就得改模型转化的代码。如果，两者齐头并进，则像我第一段说的那样做。
> > 总的来说，产生这个原因的问题在于：这个只是部署测试的例子， 原始模型在我选的这个版本中，并没有达到私有部署的效果。如果他现在的版本，或者我选的这个版本的算法效果符合你的需求，或者你坚信后期版本会达到你的效果，那么，两者都做吧。
> 
> 由于出现过版本重大修复，我使用2.0.2.1的版本做模型转化， 会显示”**无法识别的网络结构**“。作者是用2.0.2版本做的吗？是否是我使用方法问题，还是说因为版本不兼容？
> 
> 如果是版本不兼容，我想要希望您可以给我2.0.2的训练代码。感激不尽。

因为我没训练过，所以。我使用的是2.0.2版本的代码，里面貌似是包含了训练代码的。你按照我的方式，写一个最新版本的转trt脚本吧。 不能转的算子，参考我的更改方式，更改就行，新的情况，你只能自己看trt文档了。实在不行，你先onnx替代吧。
